In [23]:
import pandas as pd
import numpy as np
import collections
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
import csv
from sklearn.model_selection import RepeatedKFold

# Python script for confusion matrix creation
# Skrip python untuk pembuatan matriks
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score

#Import scikit-learn metrics module for accuracy calculation
#Import modul metrik scikit-learn untuk perhitungan akurasi
from sklearn import metrics

In [33]:
# membaca data pada format csv
df = pd.read_csv("datadamin.csv")
# melihat data set sebanyak 10 baris
df.head(10)

  Buying  Maint  Doors  Persons lug_boot Safety  Class
0  vhigh  vhigh      2        2    small    low  unacc
1  vhigh  vhigh      2        2    small    med  unacc
2  vhigh  vhigh      2        2    small   high  unacc
3  vhigh  vhigh      2        2      med    low  unacc
4  vhigh  vhigh      2        2      med    med  unacc
5  vhigh  vhigh      2        2      med   high  unacc
6  vhigh  vhigh      2        2      big    low  unacc
7  vhigh  vhigh      2        2      big    med  unacc
8  vhigh  vhigh      2        2      big   high  unacc
9  vhigh  vhigh      2        4    small    low  unacc

In [25]:
#mengganti setiap atribut menjadi angka agar mudah untuk diolah
df['Buying'] = df['Buying'].replace({'vhigh': 1, 'high': 2, 'med': 3, 'low':4})
df['Maint'] = df['Maint'].replace({'vhigh': 1, 'high': 2, 'med': 3, 'low':4})
df['lug_boot'] = df['lug_boot'].replace({'small': 1, 'med': 2, 'big': 3})
df['Safety'] = df['Safety'].replace({'low': 1, 'med': 2, 'high': 3})
df['Class'] = df['Class'].replace({'acc': 1, 'unacc': 2, 'good': 3, 'vgood': 4})

In [26]:
df

     Buying  Maint  Doors  Persons  lug_boot  Safety  Class
0         1      1      2        2         1       1      2
1         1      1      2        2         1       2      2
2         1      1      2        2         1       3      2
3         1      1      2        2         2       1      2
4         1      1      2        2         2       2      2
..      ...    ...    ...      ...       ...     ...    ...
859       4      4      4        4         2       2      3
860       4      4      4        4         2       3      4
861       4      4      4        4         3       1      2
862       4      4      4        4         3       2      3
863       4      4      4        4         3       3      4

[864 rows x 7 columns]

In [27]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 6].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [28]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

In [29]:
y_pred

array([1, 1, 1, 2, 2, 4, 4, 2, 2, 1, 1, 2, 4, 2, 2, 4, 2, 3, 3, 2, 2, 2,
       1, 2, 1, 1, 1, 2, 1, 4, 1, 1, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 4,
       2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 4, 2, 4, 4, 3, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 3,
       2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 4,
       4, 2, 1, 2, 2, 2, 1, 1, 4, 1, 2, 2, 4, 4, 1, 1, 3, 1, 1, 2, 2, 2,
       2, 2, 2, 4, 1, 1, 1, 2, 2, 1, 2, 1, 4, 3, 1, 2, 1, 1, 1, 1, 2, 1,
       2, 3, 1, 2, 1, 1, 3, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2],
      dtype=int64)

In [30]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6184971098265896

In [31]:
print(confusion_matrix(y_test, y_pred))

[[13  0  4  7]
 [41 92  6  0]
 [ 1  0  0  7]
 [ 0  0  0  2]]

In [32]:
print("Classification report")
print(classification_report(y_test,y_pred))

Classification report
              precision    recall  f1-score   support

           1       0.24      0.54      0.33        24
           2       1.00      0.66      0.80       139
           3       0.00      0.00      0.00         8
           4       0.12      1.00      0.22         2

    accuracy                           0.62       173
   macro avg       0.34      0.55      0.34       173
weighted avg       0.84      0.62      0.69       173